"""add_show_on_leaderboard_to_users

Revision ID: 729a7ab81059
Revises: f6ab067da361
Create Date: 2026-03-06 12:01:27.952702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729a7ab81059'
down_revision: Union[str, None] = 'f6ab067da361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_on_leaderboard', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_on_leaderboard')
    # ### end Alembic commands ###
