"""add_answer_sheet_soft_delete

Revision ID: e08fd89ac436
Revises: 729a7ab81059
Create Date: 2026-03-06 13:39:00.862894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08fd89ac436'
down_revision: Union[str, None] = '729a7ab81059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_sheets', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('answer_sheets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_answer_sheets_is_deleted'), 'answer_sheets', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_sheets_is_deleted'), table_name='answer_sheets')
    op.drop_column('answer_sheets', 'deleted_at')
    op.drop_column('answer_sheets', 'is_deleted')
    # ### end Alembic commands ###
